### ISSUE TITLE
Connect learner survivalsvm from package survivalsvm

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3learners#100]
## Checklist before requesting a review

- [x] Run `styler::style_pkg(style = styler::mlr_style)` (install `pat-s/styler@mlr-style` if not yet done)

- [x] Run `lintr::lint_package()` and fix all issues.

- [x] Run `usethis::use_tidy_description()` to format the `DESCRIPTION` file.

- [x] Check that the learner package name is all lower case, e.g. `mlr3learners.partykit`.

- [x] Ensure that there are not leftover of `<package>`, `<algorithm>` or `<type>` within the learner repo.

- [x] Ensure that the "Parameter Check" passed in the CI (both for the train **and** predict functions)

- [x] Ensure that "R CMD check" passed in the CI.

- [x] Check that your learners upstream package is **not** listed in the "Imports" but in the "Suggests" section within the `DESCRIPTION` file.

- [x] If you changed any parameter defaults: Did you document the change (reason and new default) in the help page of the respective learner?

- [x] Open a Pull Request in the mlr3learners repo to add your learner to the list of ["In Progress" learners](https://mlr3learners.mlr-org.com/dev/articles/learners/additional-learners.html#in-progress-1). Once approved, it will be moved to the "Approved" section.

**Comment by RaphaelS1** [comment]
Ready for review!

**Comment by pat-s** [comment]
If you use bibtex citations you need to 

- add bibtex to Suggests
- add 

```
RdMacros:
    mlr3misc
```

to DESC and run `usethis::use_tidy_description()`

The CI error on macOS-devel relates to Hmisc and can be ignored.

**Comment by RaphaelS1** [comment]
> If you use bibtex citations you need to

I removed bibtex citations, there shouldn't be any left? Unless your telling me to convert them to bibtex?

**Comment by pat-s** [comment]
Looks like all these warnings are coming from mlr3proba: https://github.com/mlr3learners/mlr3learners.survivalsvm/actions/runs/78846251

Probably because bibtex does not get installed because its in suggest. Fine, all good!

Ready to deploy 🚀

**Comment by RaphaelS1** [comment]
I'm going to publish next distr6 version, then next mlr3proba(and fix the bibtex stuff), then I'll deploy this (remove remotes) and start transferring more learners :)

**Comment by RaphaelS1** [comment]
set to deploy, will pass and deploy once mlr3proba is fully built on cran
