### ISSUE TITLE
Connect learner `penalized` from package `penalized`

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3learners#102]
## Checklist before requesting a review

- [x] Run `styler::style_pkg(style = styler::mlr_style)` (install `pat-s/styler@mlr-style` if not yet done)

- [x] Run `lintr::lint_package()` and fix all issues.

- [x] Run `usethis::use_tidy_description()` to format the `DESCRIPTION` file.

- [x] Check that the learner package name is all lower case, e.g. `mlr3learners.partykit`.

- [x] Ensure that there are not leftover of `<package>`, `<algorithm>` or `<type>` within the learner repo.

- [x] Ensure that the "Parameter Check" passed in the CI (both for the train **and** predict functions)

- [x] Ensure that "R CMD check" passed in the CI.

- [x] Check that your learners upstream package is **not** listed in the "Imports" but in the "Suggests" section within the `DESCRIPTION` file.

- [x] If you changed any parameter defaults: Did you document the change (reason and new default) in the help page of the respective learner?

- [x] Open a Pull Request in the mlr3learners repo to add your learner to the list of ["In Progress" learners](https://mlr3learners.mlr-org.com/dev/articles/learners/additional-learners.html#in-progress-1). Once approved, it will be moved to the "Approved" section.

**Comment by RaphaelS1** [comment]
Ready for review!

https://github.com/mlr3learners/mlr3learners.penalized

**Comment by pat-s** [comment]
- [ ] Remove https://github.com/mlr3learners/mlr3learners.penalized/blob/570ba667f5436446eb9ba73b4f61aaadd4a42ade/R/LearnerSurvPenalized.R#L27

- [ ] Turn off the Wiki and Projects panes (I did this for almost all learners recently)


otherwise: 👍 👍 You're on a roll

**Comment by RaphaelS1** [comment]
thanks deployed, doing next one now

**Comment by pat-s** [comment]
don't forget to add it to the learners table :)

**Comment by RaphaelS1** [comment]
ah i made a branch but forgot to PR, doing it now
