### ISSUE TITLE
Connect learner rfsrc from package randomForestSRC

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3learners#107]
## Checklist before requesting a review

- [x] Run `styler::style_pkg(style = styler::mlr_style)` (install `pat-s/styler@mlr-style` if not yet done)

- [x] Run `lintr::lint_package()` and fix all issues.

- [x] Run `usethis::use_tidy_description()` to format the `DESCRIPTION` file.

- [x] Check that the learner package name is all lower case, e.g. `mlr3learners.partykit`.

- [x] Ensure that there are not leftover of `<package>`, `<algorithm>` or `<type>` within the learner repo.

- [x] Ensure that the "Parameter Check" passed in the CI (both for the train **and** predict functions)

- [x] Ensure that "R CMD check" passed in the CI.

- [x] Check that your learners upstream package is **not** listed in the "Imports" but in the "Suggests" section within the `DESCRIPTION` file.

- [x] If you changed any parameter defaults: Did you document the change (reason and new default) in the help page of the respective learner?

- [x] Open a Pull Request in the mlr3learners repo to add your learner to the list of ["In Progress" learners](https://mlr3learners.mlr-org.com/dev/articles/learners/additional-learners.html#in-progress-1). Once approved, it will be moved to the "Approved" section.

**Comment by pat-s** [comment]
I am wondering if for this learner we should also directly add the classif and regr ones. However, you probably would like to only focus on the survival ones for now. 

Maybe a SA can help here and make this learner somehow complete right from the start?

**Comment by RaphaelS1** [comment]
Before doing anything that combines classif & regr in a `proba` related package, we first need to work out how best to merge the autotests because currently instead of opening a proba specific PR to mlr3 I just copied the autotest to proba and changed relevant parts. We will have to sort this out before I add any learners to `mlr3` or `mlr3learners`, so maybe we should wait until that before adding classif or regr to this

**Comment by RaphaelS1** [comment]
Also ready for review!

**Comment by pat-s** [comment]
I don't understand. I meant the classical classif and regr learners for this package?

**Comment by RaphaelS1** [comment]
I overloaded the autotest in proba, instead of using a conditional, which means that it would crash for classif and regr learners.

**Comment by pat-s** [comment]
Ah now I understand - you mean this issue applies to all learners that are not only proba learners?

**Comment by RaphaelS1** [comment]
Regr and classif added, checklist gone through. Ready for review!

**Comment by pat-s** [comment]
Thanks, looks good!

**Comment by RaphaelS1** [comment]
thanks deployed!
