### ISSUE TITLE
Connect learner nnet & multinom from package nnet

### ISSUE THREAD

**Issue by henrifnk** [mlr-org/mlr3learners#113]
You can find `mlr3learners.nnet` [here](https://github.com/henrifnk/mlr3learners.nnet).
I'll move the learner to `mlr3learners` and do drat once your review is done

## Checklist before requesting a review

- [x] Run `styler::style_pkg(style = styler::mlr_style)` (install `pat-s/styler@mlr-style` if not yet done)

- [x] Run `lintr::lint_package()` and fix all issues.

- [x] Run `usethis::use_tidy_description()` to format the `DESCRIPTION` file.

- [x] Check that the learner package name is all lower case, e.g. `mlr3learners.partykit`.

- [x] Ensure that there are not leftover of `<package>`, `<algorithm>` or `<type>` within the learner repo.

- [x] Ensure that the "Parameter Check" passed in the CI (both for the train **and** predict functions)

- [x] Ensure that "R CMD check" passed in the CI.

- [x] Check that your learners upstream package is **not** listed in the "Imports" but in the "Suggests" section within the `DESCRIPTION` file.

- [x] If you changed any parameter defaults: Did you document the change (reason and new default) in the help page of the respective learner?

- [x] Open a Pull Request in the mlr3learners repo to add your learner to the list of ["In Progress" learners](https://mlr3learners.mlr-org.com/dev/articles/learners/additional-learners.html#in-progress-1). Once approved, it will be moved to the "Approved" section.

**Comment by henrifnk** [comment]
[mlr3learners.nnet](https://github.com/henrifnk/mlr3learners.nnet) is ready for review now.

**Comment by pat-s** [comment]
- [ ] Watch out for the correct repo description: "Learner from {nnet} package for mlr3 "

- [ ] This reads weak: https://github.com/henrifnk/mlr3learners.nnet/blob/e71366f73cbb8a268f889e9678d501d013981542/R/LearnerClassifnnet.R#L13. If it has no default, it can not have an entry in "actual default". Please check again.

- [ ] Try to format the paramtest test files a bit more (l.15++)

- [ ] The predict functions must also be tested in the ParamTest

- [ ] The multinom learner already lives in {mlr3learners}

**Comment by henrifnk** [comment]
> The predict functions must also be tested in the ParamTest

can you send me a link to an example where this is used?

**Comment by pat-s** [comment]
all learners in {mlr3learners}

**Comment by henrifnk** [comment]
[mlr3learners.nnet](https://github.com/henrifnk/mlr3learners.nnet) is ready for another review now.

**Comment by mllg** [comment]
In https://github.com/mlr-org/mlr3extralearners.
