### ISSUE TITLE
Connect learner npudens from package np 

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3learners#119]
## Checklist before requesting a review

- [x] Run `styler::style_pkg(style = styler::mlr_style)` (install `pat-s/styler@mlr-style` if not yet done)

- [x] Run `lintr::lint_package()` and fix all issues.

- [x] Run `usethis::use_tidy_description()` to format the `DESCRIPTION` file.

- [x] Check that the learner package name is all lower case, e.g. `mlr3learners.partykit`.

- [x] Ensure that there are not leftover of `<package>`, `<algorithm>` or `<type>` within the learner repo.

- [x] Ensure that the "Parameter Check" passed in the CI (both for the train **and** predict functions)

- [x] Ensure that "R CMD check" passed in the CI.

- [x] Check that your learners upstream package is **not** listed in the "Imports" but in the "Suggests" section within the `DESCRIPTION` file.

- [x] If you changed any parameter defaults: Did you document the change (reason and new default) in the help page of the respective learner?

- [x] Open a Pull Request in the mlr3learners repo to add your learner to the list of ["In Progress" learners](https://mlr3learners.mlr-org.com/dev/articles/learners/additional-learners.html#in-progress-1). Once approved, it will be moved to the "Approved" section.

**Comment by RaphaelS1** [comment]
Ready for review!

https://github.com/mlr3learners/mlr3learners.np

**Comment by pat-s** [comment]
- [ ] Watch out for the repo description: "Learners from package {np} for mlr3". Applies to all recent learners.

- [ ] Can such things stay in one line? Looks a bit ugly splitting up the curlies: https://github.com/mlr3learners/mlr3learners.np/blob/3b17c8c7854a35076695d8188533ce300db852e1/R/LearnerDensMixed.R#L87-L88

OK otherwise 👍

**Comment by RaphaelS1** [comment]
> Can such things stay in one line? Looks a bit ugly splitting up the curlies: https://github.com/mlr3learners/mlr3learners.np/blob/3b17c8c7854a35076695d8188533ce300db852e1/R/LearnerDensMixed.R#L87-L88

Ah might have happened with styler or something,fixed. thanks

**Comment by pat-s** [comment]
> Ah might have happened with styler or something,fixed. thanks

Could be, not sure how styler handles that edge case. No worries!

**Comment by RaphaelS1** [comment]
Yeah just got picked up on lintr. Do you want me to change back or use #nolint?

**Comment by pat-s** [comment]
Ahh 😆 
Up to you here I'd say - as long as we stay consistent in all other packages :)

**Comment by RaphaelS1** [comment]
in which case I prefer to use #nolint and keep it looking more tidy, I'll deploy now
