### ISSUE TITLE
glmnet with a single feature

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr3learners#12]
glmnet does not allow training if the dataset has only a single feature,

See here in the glmnet code

```
    np = dim(x)
    if (is.null(np) | (np[2] <= 1)) 
        stop("x should be a matrix with 2 or more columns")
```

How should we handle this?

**Comment by mllg** [comment]
Options:

1. Try to get this fixed upstream
2. Fit a regular glm instead
3. Add a constant feature before fitting
4. Document this and disable the tests which trigger the exception

3+4 could get nasty during feature selection.

**Comment by mllg** [comment]
We have disabled the tests.
