### ISSUE TITLE
Connect learner sm.density from package sm

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3learners#122]
https://github.com/mlr3learners/mlr3learners.sm

## Checklist before requesting a review

- [x] Run `styler::style_pkg(style = styler::mlr_style)` (install `pat-s/styler@mlr-style` if not yet done)

- [x] Run `lintr::lint_package()` and fix all issues.

- [x] Run `usethis::use_tidy_description()` to format the `DESCRIPTION` file.

- [x] Check that the learner package name is all lower case, e.g. `mlr3learners.partykit`.

- [x] Ensure that there are not leftover of `<package>`, `<algorithm>` or `<type>` within the learner repo.

- [x] Ensure that the "Parameter Check" passed in the CI (both for the train **and** predict functions)

- [x] Ensure that "R CMD check" passed in the CI.

- [x] Check that your learners upstream package is **not** listed in the "Imports" but in the "Suggests" section within the `DESCRIPTION` file.

- [x] If you changed any parameter defaults: Did you document the change (reason and new default) in the help page of the respective learner?

- [x] Open a Pull Request in the mlr3learners repo to add your learner to the list of ["In Progress" learners](https://mlr3learners.mlr-org.com/dev/articles/learners/additional-learners.html#in-progress-1). Once approved, it will be moved to the "Approved" section.

**Comment by RaphaelS1** [comment]
Ready for review, the errors are due to this: https://cran.r-project.org/web/checks/check_results_sm.html

**Comment by pat-s** [comment]
- [ ] watch style: Replace `<-` by `=`

- [ ] indention does not follow the mlr-style

**Comment by RaphaelS1** [comment]
> indention does not follow the mlr-style

Not entirely sure which part this refers to, I ran styler again and there was a minor change to one parameter but apart from that not sure which part is not in the right style

**Comment by pat-s** [comment]
Ah I always get the wording wrong: "indentation" - 2 spaces instead of 4.

styler did this in your last commit: https://github.com/mlr3learners/mlr3learners.sm/commit/3e146f68b4941fe292606a08ba96090a02c36f85

**Comment by RaphaelS1** [comment]
okay thanks, will deploy now then
