### ISSUE TITLE
Connect learner pendensity from package pendensity

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3learners#123]
https://github.com/mlr3learners/mlr3learners.pendensity

## Checklist before requesting a review

- [x] Run `styler::style_pkg(style = styler::mlr_style)` (install `pat-s/styler@mlr-style` if not yet done)

- [x] Run `lintr::lint_package()` and fix all issues.

- [x] Run `usethis::use_tidy_description()` to format the `DESCRIPTION` file.

- [x] Check that the learner package name is all lower case, e.g. `mlr3learners.partykit`.

- [x] Ensure that there are not leftover of `<package>`, `<algorithm>` or `<type>` within the learner repo.

- [x] Ensure that the "Parameter Check" passed in the CI (both for the train **and** predict functions)

- [x] Ensure that "R CMD check" passed in the CI.

- [x] Check that your learners upstream package is **not** listed in the "Imports" but in the "Suggests" section within the `DESCRIPTION` file.

- [x] If you changed any parameter defaults: Did you document the change (reason and new default) in the help page of the respective learner?

- [x] Open a Pull Request in the mlr3learners repo to add your learner to the list of ["In Progress" learners](https://mlr3learners.mlr-org.com/dev/articles/learners/additional-learners.html#in-progress-1). Once approved, it will be moved to the "Approved" section.

**Comment by RaphaelS1** [comment]
Ready for review!

**Comment by pat-s** [comment]
- [ ] watch style: Replace `<-` by `=`

- [ ] https://github.com/mlr3learners/mlr3learners.pendensity/blob/f98a6755f590d6415421767de24f6d484763676c/R/LearnerDensPenalized.R#L74 should have curlies

- [ ] indention does not follow the mlr-style

**Comment by RaphaelS1** [comment]
>  indention does not follow the mlr-style

Re-run styler, does this apply to the one-line if statement?

**Comment by pat-s** [comment]
Not sure what you mean - you can see the changes in the commit diff? https://github.com/mlr3learners/mlr3learners.pendensity/commit/a4221541cbc40ea6e391d472a92d8f3bebc85d69

So yeah, everything looks good now :)

**Comment by RaphaelS1** [comment]
deployed
