### ISSUE TITLE
more unit tests in auto testing

### ISSUE THREAD

**Issue by QuayAu** [mlr-org/mlr3learners#13]
- test every predict type (prob and response, se and response)
- test binary and multiclass (not only multiclass)

**Comment by mllg** [comment]
* test weights (as soon as at least one learner supports this)

**Comment by mllg** [comment]
* importance function

NB: https://codecov.io/gh/mlr-org/mlr3learners/tree/master/R is useful to spot stuff which is not tested at all.

**Comment by mllg** [comment]
Importance is now tested.

**Comment by mllg** [comment]
Most stuff is tested, no need to keep this one open anymore.
