### ISSUE TITLE
Ranger: mtry and filtering

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3learners#137]
Currently, we require ranger's mtry to be an integer. If we provide `mtry > p` (where p is number of features), ranger errors. 

This leads to the following problem:
- If I use ranger together with a filter / constant feature removal I can not properly set `mtry = p`; 
Given we filter out a different amount of features in each replication, There is no way to specify to use all features, as this number will be different from fold to fold.

- Tuning mtry is also difficult, because runs for `mtry` close or equal to `p` might fail on some folds. 
  If we e.g. have sparse features this effect can be large!

Per ranger's [documentation](https://www.rdocumentation.org/packages/ranger/versions/0.12.1/topics/ranger)
`mtry` can also be a "single argument function returning an integer". 

Possible solutions:
- Instead of an `error`, do `mtry = min(mtry, p)` and throw a warning.
  This could either be changed within ranger or within the mlr3 learner.
- Give the user the option to supply a `single argument function`. This way the user would at least have the option to fix such runs.

**Comment by pat-s** [comment]
We could default to `mtry_power` also, as you did in for the old mlr2 custom learner?
I used it in my paper where I combined FS with tuning (including mtry).

How about

- Having `mtry_power` as the default [0,1] (the name could stay as `mtry`, we just document it in the help page of the learner)
- If a user sets a numeric, this is also accepted and adjusted internally

Another approach, that would maybe be somewhat cleaner and keep backward rep, is to add an extra `mtry_power` and assert internally that only one of `mtry_power` and `mtry` can be set at the same time.

**Comment by pfistfl** [comment]
The question is if we want to alter learner behavior here.

As I said, we could also just allow `mtry` to be a `function` (as it is anyway per ranger's documentation). Then all of the above could be achieved using a `trafo`.

**Comment by pat-s** [comment]
Yeah sounds also good and is most likely the least invasive change.

How would we pass the ParamInt assertion when one passes a function? Changing the param type directly would result in backward comp issues.

**Comment by mb706** [comment]
make `mtry` a `ParamUty`, with custom check function `function (x) if (!test_int(x) && !test_function(x, nargs = 1)) "Must be an integer value or a function with one argument" else TRUE`. I don't think this would cause many backwards compatibility issues because it is removing restrictions, not adding restrictiosn? A Hiwi should be able to do this.

**Comment by mllg** [comment]
I've implemented `mtry.ratio` to finally get over it.
