### ISSUE TITLE
glmnet test fails sporadically

### ISSUE THREAD

**Issue by mboecker** [mlr-org/mlr3learners#15]
When running rtest, I noticed this error, which was not present the next time I ran rtest.
After ~10 more runs, this happened again. So this is a sporadic error.

> test_classif_glmnet.R:6: failure: autotest
> `result` isn't true.
> [train()] learner 'classif.glmnet:response' on task 'feat_all_binary' failed: train log has errors: Ersetzung hat Länge 0

**Comment by mllg** [comment]
Can you provide a `sessionInfo()`? I have trouble reproducing it.

**Comment by mboecker** [comment]
of course

```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS: /usr/lib/libblas.so.3.8.0
LAPACK: /usr/lib/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=de_DE.UTF8       LC_NUMERIC=C             
 [3] LC_TIME=de_DE.UTF8        LC_COLLATE=de_DE.UTF8    
 [5] LC_MONETARY=de_DE.UTF8    LC_MESSAGES=de_DE.UTF8   
 [7] LC_PAPER=de_DE.UTF8       LC_NAME=C                
 [9] LC_ADDRESS=C              LC_TELEPHONE=C           
[11] LC_MEASUREMENT=de_DE.UTF8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.3
```

**Comment by mllg** [comment]
`sessionInfo()` must be called after triggering the bug, I don't see what packages are loaded otherwise.

Also, please make sure that you have the latest packages installed (via `devtools::update_packages()` and `devtools::install()` in the root directory of mlr3learners).

**Comment by mboecker** [comment]
Updating the packages appearently fixed the problem, thanks.
Will remember to update my packages before reporting a bug now.

**Comment by mllg** [comment]
No worries.  :+1:
