### ISSUE TITLE
Add quanteda.textmodels::textmodel_nb to mlr3extralearners

### ISSUE THREAD

**Issue by andreassot10** [mlr-org/mlr3learners#157]
This is Step 1 from the list on https://mlr3learners.mlr-org.com/.

**Comment by pat-s** [comment]
@andreassot10 Please follow the issue template for learner requests. Thanks.

**Comment by andreassot10** [comment]
Following the instructions on https://mlr3learners.mlr-org.com/ under "Requesting/Adding Additional Learners", step 1 seems to be suggesting that I should first open an issue in `mlr3learners`, which is what I've done here. Am I misunderstanding something? If yes, where's the so-called "issue template"?

**Comment by pat-s** [comment]
If you create a new issue you see an issue template. You can ignore it and end up with non-descriptive issue, as in your case. 

Please create a new issue and follow the issue template, thanks.
