### ISSUE TITLE
ranger default for num.threads

### ISSUE THREAD

**Issue by bommert** [mlr-org/mlr3learners#170]
When using a ranger learner in a variable importance filter on a high performance compute cluster, I experienced the situation that ranger by default used as many threads as there are cpus on the compute node. But I had only reserved one core, so the threads were run sequentially, as I was told by the compute cluster administrator. Clearly, I did not read the ranger documentation well enough. Since I believe that I will not be the last person to run into this issue, I wanted to report it.

**Comment by RaphaelS1** [comment]
I second this request as it directly relates to: https://github.com/mlr-org/mlr3/issues/546
I'll try and PR a fix for this if I get some time
