### ISSUE TITLE
How to update mlr3 library in Rstudio

### ISSUE THREAD

**Issue by Nehagupta90** [mlr-org/mlr3learners#192]
I was using mlr3 library from few weeks and now suddenly I am getting the following error:

Loading required package: mlr3 Error: package or namespace load failed for ‘mlr3’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): namespace ‘data.table’ 1.13.0 is already loaded, but >= 1.13.6 is required Error: package ‘mlr3’ could not be loaded

I dont know how to update the package because the version 1.13.6 is not available in the Tools menu of R studio.

**Comment by mllg** [comment]
Call `update.packages()` in a fresh R session to get `data.table` (and proboably many other packages) updated, then try again.
