### ISSUE TITLE
define API, test procedures and "learner sematics" protocol

### ISSUE THREAD

**Issue by Coorsaa** [mlr-org/mlr3learners#2]
Things we need:

- id
- name (includes type)
- hyperparameters (paradox)
- ...

**Comment by mllg** [comment]
Which API do you mean? For `train()` and `predcit()` of the learners?

**Comment by Coorsaa** [comment]
i meant the whole process from learner construction, training, prediction, ...

**Comment by berndbischl** [comment]
well, we need to define everything, that an external user would need to know to implement a learner, define slots and meta data (paramset, name, properties, there is quite a lot) and how testing works

**Comment by berndbischl** [comment]
also note that a learner will have quite a few more potential functions then just train and predict.

there is 
  getFeatureImportance
  getOOB
  and so on
we should at least make a list

**Comment by mllg** [comment]
We have autotests and the additional extractors are documented in ?Learner.
