### ISSUE TITLE
svm predict fails with callr

### ISSUE THREAD

**Issue by be-marc** [mlr-org/mlr3learners#224]
The feature names of the task are written to the state of the learner in `$.train()` but the state is not exported from the `callr` session.  Only the fitted model is sent back the main R session. Predicting fails because `learner$state$feature_names` is empty.

https://github.com/mlr-org/mlr3learners/blob/fe8d03fadf2900224c9af0dbe236207291ed9d32/R/LearnerClassifSVM.R#L79

**Comment by mllg** [comment]
Fixed in eae2c14.
