### ISSUE TITLE
[BUGLRN] Bugs in learner lda: variable appears to be constant within groups

### ISSUE THREAD

**Issue by MislavSag** [mlr-org/mlr3learners#230]
### Expected Behaviour

classif.lda works as expected.

### Actual Behaviour

It returns an error:
```
Error in lda.default(x, grouping, ...) : 
  variable 44 appears to be constant within groups
```

### Reprex

```
task_ = tsk("german_credit")
task_$task_type
learner = lrn("classif.lda")
learner$predict_sets = c("train", "test")
learner$predict_type = "prob"
fm = learner$train(task_)
```

**Comment by sebffischer** [comment]
This does not really seem like a mlr3 bug to me @mllg

**Comment by mllg** [comment]
This yields the same error:

```r
library(MASS)
data = as.data.frame(tsk("german_credit")$data())
lda(credit_risk ~ ., data = data)
```


There is a problem with the data after converting the data to a matrix (from `MASS:::lda.formula()`) and thereby dummy encoding the factors:
```r
m = model.frame(data)
grouping <- model.response(m)
x <- model.matrix(Terms, m)
xint <- match("(Intercept)", colnames(x), nomatch = 0L)
if (xint > 0L) 
  x <- x[, -xint, drop = FALSE]
```

If you now look into the 44th column, grouped by credit risk, you see that there is no observation labeled with "1":

```r
ftable(x[, 44] ~ data$credit_risk)


                 x[, 44]   0
data$credit_risk
good                     700
bad                      300
```

You can control the tolerance for the singular matrix detection via parameter `tol`, but having a constant feature will always result in an error.

**Comment by mllg** [comment]
FWIW, you can "repair" the learner via the robustify pipeline:

```r
learner = as_learner(ppl("robustify") %>>% lrn("classif.lda"))
learner$param_set$values$encode.method = "treatment" # otherwise we have colinear features
learner$train(task)
learner$predict(task)
```
