### ISSUE TITLE
Expose learner plot functions

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3learners#25]
Many learners bring their own plot functions. As we now only maintain few learners we can  maybe expose selected plots. 

Example: rpart plot, xgboost has plots etc.

**Comment by jakob-r** [comment]
Can't i simply call `plot(lrn$model)` in those cases. I think that is easy enough.

**Comment by pfistfl** [comment]
If the model actually has a `plot()` method. 
If this is not the case, I would have to go to the package, find the correct code and so on.

I think simply having a $plot() method would be a very cool thing and it would not be hard to maintain, given that we only have a few learners.

Examples:
- We could add the `rpart.plot` methods from the rpart.plot method from the `rpart.plot` package with some very sensible defaults, as the plots from only the  base package are often not really usable.

- In xgboost it is for example `xgb.plot.tree(model = bst)` instead of plot(). This is info I would need to search for.

**Comment by jakob-r** [comment]
Hmm. Seems like a nice to have.

**Comment by mllg** [comment]
See https://github.com/mlr-org/mlr3viz/issues/4.
