### ISSUE TITLE
mlr3learners site down

### ISSUE THREAD

**Issue by PhilippBach** [mlr-org/mlr3learners#262]
Dear maintainers of the `mlr3learners` package, 

thanks for all your efforts to support so many useful learners in R 🙏  

I don't know if you have already seen it, but the page <https://mlr3learners.mlr-org.com/> is currently down. I can't really see why it's down but maybe you have an idea how to fix it...

Here's the log from our failed docu deploy https://github.com/DoubleML/doubleml-docs/actions/runs/3829881478/jobs/6517060656 (search in the log for *broken*) if that's helpful

Thanks again and best, 

Philipp

**Comment by be-marc** [comment]
Hey Phillip, thanks for reporting. We switched the domain provider. I am on it.

**Comment by be-marc** [comment]
Works again.

**Comment by PhilippBach** [comment]
Great, thank you! Hope the switch went well :)
