### ISSUE TITLE
automatic tests for all learners

### ISSUE THREAD

**Issue by Coorsaa** [mlr-org/mlr3learners#3]
One (!) test for all learners, i.e. new learners should be testet automatically

- learner properties
- does prediction work?
- tests should be fast
- test predictive performance with simple examples, e.g. better than mmce of 0.3

````helper_learners_all```` could be a starting point

**Comment by mllg** [comment]
https://github.com/mlr-org/mlr3/blob/master/inst/testthat/helper_expectations.R

This file can be included in this package (see https://github.com/mlr-org/mlr3db/blob/master/tests/testthat/helper.R#L2), and `expect_learner` be extended for this purpose.

**Comment by mllg** [comment]
Should be done.
