### ISSUE TITLE
general learner test for label switching

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3learners#33]
we now already had this issue #32 
and we had this issue multiple times in mlr2

do we have a general unit test to detect this? for all learners?

**Comment by 001ben** [comment]
I had a crack at adding a unit test, I made sure it would have picked up #32, see PR for more detail

**Comment by mllg** [comment]
AFAICT there was no label switch in a classical sense in #32, the resulting predictions were correctly stored. The positive label was switched for xgboost internally, but this is only an issue if you set thresholds for early stopping in combination with some binary classification measures. The returned labels were correct.

> do we have a general unit test to detect this? for all learners?

Yes we do: https://github.com/mlr-org/mlr3/blob/master/inst/testthat/helper_autotest.R#L131

This is based on a "sanity" task, i.e. a very easy to learn task where each learner should perform reasonably well.

@001ben thanks for you PR, but I'm afraid that your PR is not needed.

**Comment by 001ben** [comment]
Ah! no problem then, It's true this only affected internals of xgboost, i thought that may have been the issue mentioned by @berndbischl as opposed to the label switching in the output from mlr3
