### ISSUE TITLE
Add "last mlr3 revision date" when loading learners?

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3learners#37]
I was wondering if we should add .onLoad message to each (custom) learner showing at which package version of the underlying package the hyperparameters of this mlr3-learner have been checked on last?

**Comment by berndbischl** [comment]
what exactly do you mean with checked? and what would such a message look like?

**Comment by pat-s** [comment]
"checked" = someone checked that the hyperpars in the mlr3learner are up-to-date with the latest release of the upstream pkg.

While some learners might stay stable, others will change param names or add new params (I am thinking of xgboost in particular).

While this approach would have been very annoying in mlr2 since this would have triggered 80+ messages, it would be acceptable in mlr3 because learners are loaded selectively.

Only `library(mlr3learners)` would trigger a bit more messages.
We could handle messages with a general verbosity options or similar.

A message could look like

```r
library(<some learner>)
# Params of <learnerXY> based on pkg version X.Y.Z
```

Of course this would involve regular checks of learners against the upstream package. But this should be done anyhow by the maintainer of the respective learner.

## What is the purpose?

If a user loads a learner and something does not work correctly, one can check the last "check date" of the learner and quickly see if that version is older than the pkg version of the upstream learner. In case a new upstream param is missing, this would be expected then and the user could easily raise a PR.

Right now, no one knows when we (or other mlr3learner maintainers) last checked the params of a learner.

**Comment by pat-s** [comment]
ping @berndbischl

**Comment by pat-s** [comment]
The more I think about this, the more important I find it.

Since we are wrapping learners, we should really be verbose in telling the user at which upstream pkg version one is accessing the learner.

We could do this in `.onLoad()`. This means we would get as many lines during startup as # of learners we provide.
For custom learners this would be less then.

Yes, this would also come with the need of updating these versions as upstream packages get updated. But this is an acceptable maintenance task and often does not require more action than updating the NEWS file.

Regarding implementation, we could add new slot to the ParamSet, denoting its upstream package version relation.
