### ISSUE TITLE
Essential Learners

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3learners#4]
Here is a list of essential learners and their respective implementation for discussion:

* [x] Featureless. In `mlr3`.
* [x] Classification and regression trees: `rpart` (in `mlr3`). I'd like to keep this in `mlr3` as `rpart` is shipped with R and I need it to run some basic tests and examples.
* [x] Linear / Logistic Reg: `lm()`, `glm`
* [x] Penalized regression: `glmnet`
* [x] kNN: `kknn`.
* [x] Naive Bayes: `e1071`.
* [x] SVM: `e1071`
* [x] Random Forest: `ranger`. 
* [x] Boosting: `xgboost`.
* [x] Kriging: `DiceKriging`.
* [ ] Neural Network: ?

Please, share your thoughts on the implementations and what is missing in this list.

@berndbischl @jakob-r @ja-thomas @larskotthoff @pat-s @Coorsaa @florianfendt @giuseppec @mb706 @zzawadz

**Comment by pat-s** [comment]
Penalized regression -> glmnet ?

**Comment by ja-thomas** [comment]
Good multinomial model is really important, but I don't really know which package implements this (except for dnn frameworks).

Also, do we care for heavy dependencies here? Most neural net frameworks come with a lot

**Comment by berndbischl** [comment]
Glm: glmnet offers penalties so I would prefer that to get ridge and lasso. It has also become pretty standard. Also note that we need to cover enough regression, especially simple LMs.

SVMs: both are fine but libsvm is more standard. 

Knn: why not use package kknn? More flexible.

**Comment by berndbischl** [comment]
Lda. Imho not needed

**Comment by ja-thomas** [comment]
Keras has Really heavy dependencies (Python!) etc. Kind of annoying

**Comment by berndbischl** [comment]
> Keras has Really heavy dependencies (Python!) etc. Kind of annoying

better alternative or nothing?

**Comment by mllg** [comment]
> Glm: glmnet offers penalties so I would prefer that to get ridge and lasso. It has also become pretty standard. Also note that we need to cover enough regression, especially simple LMs.

AFAIK, although you can set the penalty term to 0, you don't get hypothesis tests for the betas from glmnet. So glmnet cannot replace regular linear / logistic regression.

Nevertheless, I agree that penalized regression is important and added to the list.

**Comment by ja-thomas** [comment]
I don't think there is a better alternative.
But I would suggest to not encode possible architectures in the param set but only have one architecture parameter. 

This would allow to tune over different optimizers/ learning rates etc. (everything which is set in the `compile` function), but not over the number, size and type of layers. Otherwise the paramset will get quite complex.

When we depend on keras anyways I would suggest to directly implement the multinomial model as a keras model. Or does anybody know a good package in R? There is `mnlogit` but I don't have any experience using it

**Comment by ja-thomas** [comment]
+1 for `kknn`

**Comment by ja-thomas** [comment]
What about

- AdaBoost
- Linear models by SGD (regression, binary, multiclass)
- Featureless learner
- 1R
- configurable one layer NNet (compare https://scikit-learn.org/stable/modules/neural_networks_supervised.html)

**Comment by mllg** [comment]
Featureless is in mlr3. About he other models @ja-thomas suggested: I don't consider them to be essential. More like nice to have. We should concentrate on the others first. Agreed?

**Comment by ja-thomas** [comment]
Fine with me, except maybe the Linear models by SGD, but if we implement the multiclass linear model (which we definitely want imo.) this is "free"

**Comment by berndbischl** [comment]
the conbfigurable 1layer NN is very nice. but this doesnt work if we dont have a package (or it is again keras)

**Comment by ja-thomas** [comment]
that would be keras again,

Linear SGD models, architecture based NN and configurable 1/2 layer NN would all be done in Keras.

**Comment by mb706** [comment]
What about `nnet` for single layer neural nets? Also there are `neuralnet` and `deepnet` which are not perfect but may be a compromise for anns without large dependencies.

**Comment by berndbischl** [comment]
They all suck

**Comment by Coorsaa** [comment]
Yes, this list was basically based on the one above in this issue. It could/should be updated though to the present implementation status.

**Comment by berndbischl** [comment]
if you maintain other stuff can you please crosslink this / and or clean up

**Comment by mllg** [comment]
We now have all essential learners (not all important hyperparamters are in the parameter sets though). Neural networks will probably go into an extra package.
