### ISSUE TITLE
consider moving all suggested learner packages in mlr3learners to imports

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3learners#44]
isnt it much nicer if i dont have to install all 10 learner packs manually?
@mllg

**Comment by mllg** [comment]
I get your point, but most people won't use all learners. Do we really want to force everyone to install xgboost if they just want to do k-nn? 

I'm unsure about this...

**Comment by berndbischl** [comment]
also we dont need to doc this, people should know how to install packages, and noboby - besided us - uses rt.so that does not help.

MAYBE we can do something with the mlr3verse.
but i am already also getting feedback, that to use our stuff people have to run very many library and install commands, which is certainly true.

**Comment by mllg** [comment]
* We could provide a function which installs all suggested learner packages.
* mlr3verse could also import the learner packages. However, I never understood (but also didn't ask) why the package has so much code or needs stuff like tibble, purrr, rstudioapi, cli, dplyr, ... Wouldn't a simple dummy package with a proper DESCRIPTION suffice?

**Comment by pat-s** [comment]
> mlr3verse could also import the learner packages. However, I never understood (but also didn't ask) why the package has so much code or needs stuff like tibble, purrr, rstudioapi, cli, dplyr, ... Wouldn't a simple dummy package with a proper DESCRIPTION suffice?

Back then I simply used the skeleton from the _tidyverse_ packages to have it going quickly. With more time this could certainly be made more simple.

> We could provide a function which installs all suggested learner packages.

Yes, and it could live in the _mlr3verse_ (if this is the package which aims to simplify installing everything). If we put this into _mlr3learners_ we again spread such "install-sugar" across multiple packages.

The workflow could be:

1. Use _mlr3verse_ to install and update the mlr3 ecosystem
2. Use _mlr3verse_ to install all custom learners including their packages (if you want to)

In general I would also disagree on putting all upstream packages into Imports in _mlr3learners_.

**Comment by berndbischl** [comment]
> 1. Use _mlr3verse_ to install and update the mlr3 ecosystem

ok, i think i can live with this. i mean an even simpler way would be to import the 10 learners into "verse"? wouldnt this solve everything for day2day use?

**Comment by berndbischl** [comment]
> * . However, I never understood (but also didn't ask) why the package has so much code or needs stuff like tibble, purrr, rstudioapi, cli, dplyr, ... Wouldn't a simple dummy package with a proper DESCRIPTION suffice?

looking into the package bit more now, this seems also very strange to me?
especially as we are saying: "hey we dont need all of that baggage in mlr3", but if you want to use the verse package then....

**Comment by pat-s** [comment]
> ok, i think i can live with this. i mean an even simpler way would be to import the 10 learners into "verse"? wouldnt this solve everything for day2day use?

Well then you would install all the learners already when just installing all mlr3* packages - does everyone want that? Do we want that? I would vote for an external "mlr3learner-install" function.

> especially as we are saying: "hey we dont need all of that baggage in mlr3", but if you want to use the verse package then....

Well, as said above: It was a c/p approach to be quick back then, if we rely more on it I am happy to clean it up and make it more slim.

**Comment by berndbischl** [comment]
So what exactly is installed when i install mlr3 verse? Every mlr3 package under the sun? But exactly no ml algorithm? That sounds quite weird...

**Comment by berndbischl** [comment]
it is also now inconstistent that that all extra-learner packages install the underlying package, but mlr3learners does not.
i guess i would vote to put a simple "install" function in mlr3learners.
but make the "verse" depend on all 10 learner packages. at least that last bit of convenience should be there

**Comment by pfistfl** [comment]
So when I use `mlr3verse` I use it mostly for the `mlr3verse_update()` function.
If using `mlr3verse` now requires me to install 20-30 packages, I would just stop using it.
For instance, updating mlr3learners would now also always update all packages (xgboost etc.), which compiles for quite a few seconds. Having this for every minor new xgboost version without
me even needing this is stupid. 
 
I am all for having a method that installs all suggested packages, but having them automatically imported/installed is overkill IMHO.

Proposal:

```
mlr3verse_install_suggests = function(package = NULL) {
  if (is.null(package)) # install suggests for all mlr3verse packages...
  else install_suggested(package) # install suggests for a certain package.
}
```

I guess this is something that can be communicated to a user and does not require too many 
`install_library` calls.

**Comment by mllg** [comment]
It is now properly documented how to install all suggested packages. Closing here.
