### ISSUE TITLE
Enable more xgboost parameters

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3learners#45]
What is it about [this TODO](https://github.com/mlr-org/mlr3learners/blob/6dc9ef64d7811b8be26ffab6ce1febca8c99dfd4/R/LearnerClassifXgboost.R#L60)? If this worked with mlr it should also work with mlr3? 

Please be aware that the `tree_method` `default` is *wrong* as far as I understand [the documentation of xgboost](https://xgboost.readthedocs.io/en/latest/parameter.html): The default should be `"auto"`.

**Comment by pat-s** [comment]
Haven't looked in detail but were you aware of #31?

**Comment by be-marc** [comment]
Can I use #31 as a starting point? It seems you already changed there a lot

**Comment by mb706** [comment]
Huh, wasn't aware of that.
