### ISSUE TITLE
Connect learner GauPro

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3learners#47]
https://cran.r-project.org/web/packages/GauPro/index.html

**Comment by mllg** [comment]
@jakob-r @berndbischl have you tried it for BO?

**Comment by jakob-r** [comment]
What about
- `GPfit` looks also promising
- `gptk`?
- `mlepg`?
- `kernlab::gausspr`?

**Comment by mllg** [comment]
* GPfit ist implemented in R.
* gptk also Just R, last commit is 3 years ago.
* mlepg I couldn't find.
* gausspr should be also benchmarked

**Comment by mllg** [comment]
It's mlegp.

**Comment by mllg** [comment]
GauPro does not seem to be mature enough.

**Comment by jakob-r** [comment]
according to `mlepg` is worse then their own `GPfit`. They also mention `btgp` which also has bayesian tree GPs. 
The JOSS Paper of `DiceKriging` does not contain any benchmark. Maybe somebody should really do that. Bachelor/Master Thesis?

**Comment by berndbischl** [comment]
agreeing with @jakob-r

**Comment by berndbischl** [comment]
but its maybe not a mlr3learners / software issue, more a reserach issue?

**Comment by jakob-r** [comment]
Do we have a tracker for that?

**Comment by berndbischl** [comment]
> Do we have a tracker for that?

no

**Comment by jakob-r** [comment]
We could use the mlr-docs repo as a place for that if you think it would be a good idea to have a central place for such issues.

**Comment by berndbischl** [comment]
Not really. I don't know if it's pure research we should handle this differently. I mean the problem is basically to align Dortmund and lmu here, especially for mbo.

I am super happy to talk about this and have a place for project ideas. But should we not talk about how to handle this first?
