### ISSUE TITLE
classif.kknn predicts probabilities even when predict_type is response

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3learners#50]
the learner should only predict responses if predict_type is response, and only probabilities if predict_type is probability
```r
> lrn("classif.kknn", predict_type = "response")$train(tsk("iris"))$predict(tsk("iris"))
<PredictionClassif> for 150 observations:
    row_id     truth  response prob.setosa prob.versicolor prob.virginica
         1    setosa    setosa           1       0.0000000      0.0000000
[...]
```

**Comment by pat-s** [comment]
@mboecker @be-marc Could one of you take this one and also write a generic unit test for this?

**Comment by be-marc** [comment]
@pat-s Could you change the permissions of mlr-org/mlr3 so that I can create a branch and assign myself to issues?
