### ISSUE TITLE
wiki page list does not list info optimally

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3learners#54]
the problem is basically the wikipage. it does not make clear what is a package, and the learner names are not even visible...

**Comment by berndbischl** [comment]
i am stupid, the learners are named correctly and the package too

**Comment by berndbischl** [comment]
the problem is basically the wikipage. it does not make clear what is a package, and the learner names are not even visible...

**Comment by be-marc** [comment]
Done https://github.com/mlr-org/mlr3learners/wiki

**Comment by berndbischl** [comment]
In cases like these rather wait for review pls

**Comment by berndbischl** [comment]
It's much better now. But the column names seem somewhat off. The first column seems to be the package? And the 3rd column does not contain valid learner names. And we should also mention the function of the implementing learner

**Comment by be-marc** [comment]
Maybe like this `mlr3 package | upstream package | package functions` ? Should we add a column for the implemented learners?

**Comment by pat-s** [comment]
Learner list is now available at https://mlr3learners.mlr-org.com/dev/articles/learners/additional-learners.html.
