### ISSUE TITLE
Design document for the tests

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr3learners#6]
Is somewhere defined how tests for the learner should look like?

E.g. 

- General stuff is tested in test_[type]_all.R
- Special bugs we discover for learners go in a seperate test file `test_classif_[lrn].R`

**Comment by QuayAu** [comment]
for every learner, there is a seperate test file `test_classif_[lrn]`. General stuff is tested with the `test_learner` function, which tests a leaner's features types and properties.

**Comment by mllg** [comment]
I guess we can close here. Just call `run_autotest(lrn)`. See https://github.com/mlr-org/mlr3/blob/master/inst/testthat/helper_autotest.R for details.
