### ISSUE TITLE
Connect learner bart from package dbarts

### ISSUE THREAD

**Issue by ck37** [mlr-org/mlr3learners#60]
Hello,

This is an initial issue for a dbarts implementation.

I have a draft repository which is nearly done but not passing all tests yet:
https://github.com/ck37/mlr3learners.dbarts

On classification I'm having trouble getting the sanity checks for pass, and would take any help on that.

Thanks,
Chris

**Comment by pat-s** [comment]
@be-marc Would have resources to help with the tests?

**Comment by be-marc** [comment]
@pat-s Yes

**Comment by be-marc** [comment]
The sanity check fails on this task

```
<TaskClassif:sanity> (200 x 3)
* Target: y
* Properties: twoclass
* Features (2):
  - dbl (2): unimportant, x
```

Since `classif.ce` is 1. The other tasks also have a very high ce.

@ck37 I suspect that the class labels are not correctly assigned to the result matrix in `predict()`. I can check this in two days or you can find the bug yourself.

Thanks for implementation!

**Comment by be-marc** [comment]
The predict function for the bart model returns the probabilities for the first factor level in `task$data()`

```
levels(task$data()$type)
# [1] "nonspam" "spam"
```

However, `task$class_names` seems to return the class labels with the positive class first

```
task$class_names
# [1] "spam"    "nonspam"
```

**Comment by ck37** [comment]
Ok thanks to the benevolent PR by @be-marc classification is fixed, and I've fixed regression.

I think this is ready for a review.

**Comment by ck37** [comment]
Hi @mllg, @berndbischl, @pat-s or @be-marc - are you able to give https://github.com/ck37/mlr3learners.dbarts a review?

Is it possible to add it to the wiki list as well?

Thanks,
Chris

**Comment by pat-s** [comment]
Thanks @ck37 

Please transfer the repo to the mlr3learners org and add the learner to section "awaits review" in the [wiki](https://github.com/mlr-org/mlr3learners/wiki).

It is easier for us to handle the review with write permissions to the repo :)

(and sorry for the late response, our backlog is a bit long :( )

**Comment by ck37** [comment]
I would be glad to, however to transfer the repo I would need "create repositories" permission in the mlr3learners organization (https://help.github.com/en/github/administering-a-repository/transferring-a-repository#about-repository-transfers), and to edit the wiki I would need to need to be a repository collaborator or the wiki permissions need to be changed (https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis). Or I can transfer the repo to an individual user account first.

**Comment by pat-s** [comment]
I invited you to the mlr3learners org. Sorry for that!

The mlr3learners wiki (linked above) should be editable by anyone though. Did you try to edit it?

**Comment by ck37** [comment]
Thanks, transferred!

And yep, I did try to edit the wiki but there's no edit button:

![Capture](https://user-images.githubusercontent.com/50770/72366789-ce81a100-36af-11ea-8fbf-7265ffc29a01.png)

**Comment by pat-s** [comment]
The "Restrict editing to users in teams with push access only" was checked. Does it work now?

Sorry for the troubles!

**Comment by ck37** [comment]
Cool, yep it works now

**Comment by mllg** [comment]
In https://github.com/mlr-org/mlr3extralearners.
