### ISSUE TITLE
Connect learner multinom from package nnet

### ISSUE THREAD

**Issue by fabian-s** [mlr-org/mlr3learners#65]
`mlr3learners` currently does not provide simple tuning-free softmax regression for `multiclass` tasks. 
I think it should, as a versatile and interpretable baseline against more complicated tunable algorithms (glmnet, trees, svm).

**Comment by berndbischl** [comment]
can we quickly discuss where this learner should live? in the mlr3learner package or the org as an extension package? 
i dont care whether its HP-free. it having regularization would actually potentially be an advantage to make it more robust.
i am MAYBE more in line with the argument that it can do multiclass.

@mllg ?

**Comment by mllg** [comment]
If Fabian uses this learner as a baseline, I guess we should put it in the package rather than the org. Additionally, as `nnet` is a recommended package, there is basically no additional dependency.

**Comment by berndbischl** [comment]
> If Fabian uses this learner as a baseline, I guess we should put it in the package rather than the org. Additionally, since `nnet` is a recommended package, there is basically no additional dependency.

good, fine for me
