### ISSUE TITLE
Deal with option "contrasts"

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3learners#68]
Some models rely on the global option "contrasts" (`lm`, `glm`, maybe more). This renders the fitting process irreproducible.

We should set the option to the default (`c(ordered = "contr.poly", unordered = "contr.treatment")`) and document this properly.

**Comment by mllg** [comment]
@pat-s Some problem probably applies for mlr.

**Comment by mllg** [comment]
```r
  task = tsk("boston_housing")
  learner = mlr3::lrn("regr.lm")

  learner$train(task)
  coefs1 = coef(learner$model)

  withr::with_options(list(contrasts = c(ordered = "contr.poly", unordered = "contr.poly")),
    learner$train(task)
  )
  coefs2 = coef(learner$model)

  setequal(names(coefs1), names(coefs2))
```

**Comment by pat-s** [comment]
Never heard of that option before. Will take a look, thanks.
Lot's of learners to go through - is there an easy way to see which algs rely on it?

**Comment by mllg** [comment]
IDK. I guess I'll implement an autotest for this option. Could also be a problem even if there is no exposed arg and model.matrix is called internally.
