### ISSUE TITLE
Connect learner JRip from package RWeka

### ISSUE THREAD

**Issue by henrifnk** [mlr-org/mlr3learners#77]
This is an initial issue for JRip implementation.
https://github.com/henrifnk/mlr3learners.RWeka

All check are running so far but there are is an issue left:
https://github.com/henrifnk/mlr3learners.RWeka/issues/1

Thanks,
Henri

**Comment by henrifnk** [comment]
`JRip` from `RWeka` should be running now...
I would transfer it to mlr3learners once I have your confirmation...
Btw. I saw that there were many more learners from `RWeka` connected to `mlr` like `J48` , it would be easy to add them to the `mlr3learners.RWeka` package if there is any need for them to be implemented...

**Comment by pat-s** [comment]
Thanks!

> Btw. I saw that there were many more learners from RWeka connected to mlr like J48 , it would be easy to add them to the mlr3learners.RWeka package if there is any need for them to be implemented...

Feel free to do so :)


# Review

- [ ] Please respect the mlr-style (no `<-`)
- [ ] CI needs to be green. If you have trouble installing {RWeka} have a look how we do it in mlr2
- [ ] Package Version should be "dev" until approved
- [ ] What about the regression learner?

**Comment by pfistfl** [comment]
I would suggest to finish here by adding JRip and when this is merged have PR's for the different other  learners. This makes things easier to review.

**Comment by henrifnk** [comment]
> What about the regression learner?

As I know `JRip` is a Classif-only Learner and can't handle numeric targets...

>  CI needs to be green. If you have trouble installing {RWeka} have a look how we do it in mlr2

I guess CI is gonna be green once I transfer it to the mlr3learner organization...
Actually I had no trouble installing {RWeka}, what do you mean by that?

**Comment by pat-s** [comment]
> As I know JRip is a Classif-only Learner and can't handle numeric targets...

I don't know, just asking. Did you verify this? :) 

> I guess CI is gonna be green once I transfer the repo to the mlr3learner organization...
> Actually I had no trouble installing {RWeka}, what do you mean by that?
> 

Do you know what "CI green" means? The badge is just a summary, you need to look at the individual runs:
https://github.com/henrifnk/mlr3learners.RWeka/actions

> I would suggest to finish here by adding JRip and when this is merged have PR's for the different other learners. This makes things easier to review.

Sure, this was the intention anyways 👍 
We do not need to implement all RWeka algs at once but we should have more than just one classif learner at the start :)

**Comment by berndbischl** [comment]
> Btw. I saw that there were many more learners from `RWeka` connected to `mlr` like `J48` , it would be easy to add them to the `mlr3learners.RWeka`

put everything into an mlr3learners.RWeka package, please

**Comment by berndbischl** [comment]
and yes, that does not need to contain ALL algs from WEKA as learners, and there should be individual PRs per learner

**Comment by henrifnk** [comment]
> I don't know, just asking. Did you verify this? :)

Jap i'm pretty sure :)

> Do you know what "CI green" means?

sorry for confusion I set myself into it now... still I couldn't figure out a perfect solution.
Tests are running on Ubuntu and on both macOS as well as on my windows device now (guess I have different settings on installing rJava...), but not on the ghactions windows...

The error occures on  `stage "script": script.`, where it says `<error/rlang_error>`

I skipped the tests on windows now, like you did in your [mlrcommit](https://github.com/mlr-org/mlr/commit/2bbd4fbf4cab4167fbdcfb5e7b0e69cd6eb2320c)yesterday  and CI is green...
if you have any advise
