### ISSUE TITLE
Learner inheritance

### ISSUE THREAD

**Issue by adibender** [mlr-org/mlr3learners#80]
Some learners for differnt taks are very similar except for some changes in default arguments and possibly transformation of the target, e.g. `LearnerRegrXgboost`, `LearnerClassifXgboost` and `LearnerSurvXgboost`. Currently, lots of code is duplicated with minor changes. If something changes in one of them, the other learners are not updated, which leads to (unexpectedly) different behaviour. 

@berndbischl suggested to ignore this for now

**Comment by mllg** [comment]
I agree that code duplication is problem here. But as we agreed to put learners from the same package into the same extension package, we can just avoid some duplication with (internal) helper functions, without inheritance.
