### ISSUE TITLE
Property "parallel" is not declared in learners

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3learners#83]
Even though we list it as a valid property in the [mlr3book section](https://mlr3book.mlr-org.com/extending-learners.html#learner-meta-information).

This should be checked for all learners.

**Comment by mllg** [comment]
Right now we are not doing anything with this property. I'll update the description in the book for now. In the long run, we might want to tag parameters which map to the number of cores/threads to use, and then implement something which works nicely together with `future`.
