### ISSUE TITLE
inconsistent naming: regr.glmnet

### ISSUE THREAD

**Issue by idavydov** [mlr-org/mlr3learners#90]
In the previous version of mlr there were two type of `glmnet` learners (regression):
- `regr.glmnet` using `glmnet::glmnet`
- `regr.cvglmnet` using `glmnet::cv.glmnet`

In mlr3learner there is only `regr.glmnet` currently. But instead of `glmnet::glmnet` it is using `glmnet::cv.glmnet`.

Would it maybe be possible to rename `regr.glmnet` to `regr.cvglmnet`?

**Comment by pat-s** [comment]
Yes, my plan is to change it like you described it.
