### ISSUE TITLE
Connect learners CoxBoost and cv.CoxBoost from package CoxBoost 

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3learners#92]
Ready for review when you are!

https://github.com/mlr3learners/mlr3learners.coxboost

**Comment by RaphaelS1** [comment]
I've made all changes to controls, and `lintr` is passing. Only problem is that all builds are failing and saying I need to add a PAT, which is weird because they were passing recently. Are you aware of any recent updates or changes that could have caused this? Or just a temporary bug?

**Comment by RaphaelS1** [comment]
- [ ] Run `styler::style_pkg(style = styler::mlr_style)` (install `pat-s/styler@mlr-style` if not yet done)

- [ ] Run `lintr::lint_package()` and fix all issues.

- [ ] Run `usethis::use_tidy_description()` to format the `DESCRIPTION` file.

- [ ] Check that the learner package name is all lower case, e.g. `mlr3learners.partykit`.

- [ ] Ensure that there are not leftover of `<package>`, `<algorithm>` or `<type>` within the learner repo.

- [ ] Ensure that the "Parameter Check" passed in the CI (both for the train **and** predict functions)

- [ ] Ensure that "R CMD check" passed in the CI.

- [ ] Check that your learners upstream package is **not** listed in the "Imports" but in the "Suggests" section within the `DESCRIPTION` file.

- [ ] If you changed any parameter defaults: Did you document the change (reason and new default) in the help page of the respective learner?

- [ ] Open a Pull Request in the mlr3learners repo to add your learner to the list of ["In Progress" learners](https://mlr3learners.mlr-org.com/dev/articles/learners/additional-learners.html#in-progress-1). Once approved, it will be moved to the "Approved" section.

- [ ] Rather than using custom code you can tag these control paramters with "control" in the ParamSet and then query them explicitly in `.train()`

- [ ] suggest using `mlr3misc::stopf(wrap = TRUE)`

- [ ] I am aiming that we become specific in prefixing functions from external packages, i.e. `mlr3misc::invoke(mlr3proba::predict_survreg)`

**Comment by RaphaelS1** [comment]
Checklist all checked, as well as the other bits from mlr3learners.survival.
All checks passing (apart from the mac-devel bug).
Ready for review!

**Comment by pat-s** [comment]
I've made last changes, good to go for drat deployed now ;) And moving it one level up in the learners table :)

**Comment by RaphaelS1** [comment]
Thanks! Deployed
